### ISSUE TITLE
Primary key from parent object

### ISSUE THREAD

**Issue by stasivanov** [Yalantis/FastEasyMapping#100]
Hello again. Unfortunately I need to kinda accept the JSON object's structure that I get from API without ability to change it. And it looks like this:

```
{
	"data" : [
		{
			"unique_id": "some unique id",
			"children": [
				{
					"non_unique_id" : "Some non unique ID",
					"title" : "Some title",
					"description" : "Some description",
					"another_child" : {
						"another_non_unique_id" : "Another non unique ID",
						"another_title" : "Some title that is not related to the parent.title",
						"another_description" : "Some description that is not related to the parent.description"
					}
				}
			]
		}		
	]
}

```

So, as you understand the problem is that I have child object doesn't have a unique field, and furthermore, the child of the child also doesn't have it.

I probably know the answer, but anyway I want to ask. 

As a result, I would want to simulate the uniqueIDs for sub-items. Like object in `children` would have `customUniqueID` as `parent.uniqueID + non_unique_id`, and `anotherChild` would have `anotherCustomUniqueID` as `parent.customUniqueID + another_non_unique_id`

Is something like this possible? Otherwise what is the best workaround here (if any exist)?

Thanks

**Comment by dimazen** [comment]
Hello, @stasivanov! 
I would suggest to leave backend's ID untouched and to disable uniquing for those child objects. 
Is this something you can proceed with?
