### ISSUE TITLE
Crash using relationship binding by PK

### ISSUE THREAD

**Issue by asam139** [Yalantis/FastEasyMapping#112]
The library crashes when the object which is being binding using a PK has a relationship called equal to other property that the parent object. Example:

Example of Project JSON
{
   "name": "Test",
   "id": 19,
   "membership": {
         ...
     },
   "user_group_id": 5
}

Example of UserGroup JSON
{
   "name": "Test",
   "id": 5
   "membership": {
         ...
     },
   "user_group_id": 5
}

Both object have a relationship called "membership" so when the library is doing the binding using the property "user_group_id" fails.

**Comment by dimazen** [comment]
Hello, @asam139. Thanks for your report. Can you share you `FEMMapping` description?

**Comment by asam139** [comment]
Of course: 

For class project: 

+ (FEMMapping *)defaultMapping {
    static FEMMapping *mapping = nil;
    if (!mapping) {
        mapping = [[FEMMapping alloc] initWithEntityName:NSStringFromClass(self.class)];
        mapping.primaryKey = @"id_";
        [mapping addAttributesFromDictionary:@{@"id_": @"idd",
                                               @"name": @"name",
                                               @"state": @"state",
                                               @"index": @"index",
                                               @"textFirstQuadrant": @"textFirstQuadrant",
                                               @"textSecondQuadrant": @"textSecondQuadrant",
                                               @"textThirdQuadrant": @"textThirdQuadrant",
                                               @"textFourthQuadrant": @"textFourthQuadrant",
                                               @"colorFirstQuadrant": @"colorFirstQuadrant",
                                               @"colorSecondQuadrant": @"colorSecondQuadrant",
                                               @"colorThirdQuadrant": @"colorThirdQuadrant",
                                               @"colorFourthQuadrant": @"colorFourthQuadrant",
                                               @"timestamp": @"timestamp",
                                               @"edited_by": @"edited_by",
                                               @"requestedTime": @"requested_time",
                                               @"editedByDevice": @"editedByDevice",
                                               @"ownersCountCache": @"owners_count",
                                               @"editedByUsername": @"edited_by_username",
                                               @"versionID": @"version_id",
                                               @"pm_notes": @"notes",
                                               @"templateCreationDate": @"templateCreationDate",
                                               @"creatorUsername": @"creator_username",
                                               @"accountURI": @"account_uri",
                                               @"userGroupID": @"user_group_id"}];
        [mapping addAttribute:[FEMAttribute dateAttributeWithProperty:@"creationDate" keyPath:@"creationDate"]];
        [mapping addAttribute:[FEMAttribute dateAttributeWithProperty:@"startDate" keyPath:@"startDate"]];
        [mapping addAttribute:[FEMAttribute dateAttributeWithProperty:@"endDate" keyPath:@"endDate"]];
        
        FEMRelationship *tagRelationship = [[FEMRelationship alloc] initWithProperty:@"tags" keyPath:@"tags" mapping:ListTag.defaultMapping];
        tagRelationship.toMany = YES;
        [mapping addRelationship:tagRelationship];
        
        FEMRelationship *userGroupRelationship = [[FEMRelationship alloc] initWithProperty:@"userGroup" keyPath:nil mapping:UserGroup.defaultMappingRelationshipByPK];
        userGroupRelationship.weak = YES;
        [mapping addRelationship:userGroupRelationship];
    }
    return mapping.copy;

And for UserGroup:

+ (FEMMapping *)defaultMappingRelationshipByPK {
    static FEMMapping *mapping = nil;
    if (!mapping) {
        mapping = [[FEMMapping alloc] initWithEntityName:NSStringFromClass(self.class)];
        mapping.primaryKey = @"serverID";
        [mapping addAttributesFromDictionary:@{@"delete": @"delete",
                                               @"descriptionText": @"description",
                                               @"logo": @"group_logo",
                                               @"serverID": @"user_group_id",
                                               @"isPrivate": @"is_private",
                                               @"name": @"name",
                                               @"resourceURI": @"resource_uri"}];
        [mapping addAttribute:[FEMAttribute dateAttributeWithProperty:@"creationDate" keyPath:@"creation_date"]];
        
        FEMRelationship *membershipsRelationship = [[FEMRelationship alloc] initWithProperty:@"memberships" keyPath:@"memberships" mapping:UserGroupMembership.defaultMapping];
        membershipsRelationship.toMany = YES;
        [mapping addRelationship:membershipsRelationship];
    }
    return mapping.copy;
}

Besides, I want to share some comments, I hope that it helps. I have been reviewing the code and I does not understand all code because I have had not a lot of time but I saw some inconsistencies: 

- If the relationship has not key (because it is a PK binging) maybe the method should not continue the recursion:

void _FEMRepresentationCollectObjectPrimaryKeys(id object, FEMMapping *mapping, NSMutableDictionary<NSNumber *, NSMutableSet<id> *> *container) {
    if (mapping.primaryKeyAttribute) {
        id value = FEMRepresentationValueForAttribute(object, mapping.primaryKeyAttribute);
        if (value && value != NSNull.null) {
            [[container objectForKey:mapping.uniqueIdentifier] addObject:value];
        }
    }

    for (FEMRelationship *relationship in mapping.relationships) {
         ////////////////////////////////////
        // These lines are mine
        if (!relationship.keyPath) {
            continue;
        }
       ////////////////////////////////////
        id relationshipRepresentation = FEMRepresentationRootForKeyPath(object, relationship.keyPath);
        if (relationshipRepresentation && relationshipRepresentation != NSNull.null) {
            _FEMRepresentationCollectPresentedPrimaryKeys(relationshipRepresentation, relationship.mapping, container);
        }
    }
}

- Some method can receive NSDictionary, NSNumber and NSSString but the method only is prepared to work with NSDictionary. The case:

void _FEMRepresentationCollectObjectPrimaryKeys(id object, FEMMapping *mapping, NSMutableDictionary<NSNumber *, NSMutableSet<id> *> *container) {
    if (mapping.primaryKeyAttribute) {
        ////////////////////////////////////
        // If the object is NSNumber or NSString  FEMRepresentationValueForAttribute crashes.
        ////////////////////////////////////
        id value = FEMRepresentationValueForAttribute(object, mapping.primaryKeyAttribute);
        if (value && value != NSNull.null) {
            [[container objectForKey:mapping.uniqueIdentifier] addObject:value];
        }
    }

    for (FEMRelationship *relationship in mapping.relationships) {
        id relationshipRepresentation = FEMRepresentationRootForKeyPath(object, relationship.keyPath);
        if (relationshipRepresentation && relationshipRepresentation != NSNull.null) {
            _FEMRepresentationCollectPresentedPrimaryKeys(relationshipRepresentation, relationship.mapping, container);
        }
    }
}

void _FEMRepresentationCollectPresentedPrimaryKeys(id representation, FEMMapping *mapping, NSMutableDictionary<NSNumber *, NSMutableSet<id> *> *container) {
    if ([representation isKindOfClass:[NSArray class]]) {
        for (id object in (id<NSFastEnumeration>)representation) {
            _FEMRepresentationCollectObjectPrimaryKeys(object, mapping, container);
        }
    } else if ([representation isKindOfClass:[NSDictionary class]] || [representation isKindOfClass:[NSNumber class]] || [representation isKindOfClass:[NSString class]]) {
        ////////////////////////////////////
        // This method can receive a Number or NSString
        ////////////////////////////////////
        _FEMRepresentationCollectObjectPrimaryKeys(representation, mapping, container);
    } else {
        NSCAssert(
            NO,
            @"Can not collect primary keys for a given representation.\n"
            "Expected container classes: NSArray, NSDictionary, NSNumber or NSString. Got: %@.\n"
            "Mapping: %@\nRepresentation:%@",
            NSStringFromClass([representation class]), mapping, representation
        );
    }
};
  
Sorry if I have said some without sense.
For now I am doing the bindings manually.
Thanks so much for all.

**Comment by dimazen** [comment]
Perfect. Let me make a test to see why does it crashes. 

Also, from your code you don't have to cache mapping as it shouldn't be a bottleneck during `defaultMapping`, but of course is up to you :) 

Thanks also for your comments, let me just run your code on my own to see what is going on :) 
I'll get back shortly.

**Comment by dimazen** [comment]
@asam139 I'm trying to reproduce your crash. Question: does `memberships` are of the same classes? Can you give me corresponding part of the JSON and a mapping for it as well?

**Comment by dimazen** [comment]
For now: it would be nice to have a full set of classes with fields like `id` and related relationships (`membership`, `userGroup`) as well as the JSON with the same fields (so that you can throw away sensitive data from this json).

**Comment by asam139** [comment]
Your are right, the easy way is to change keys in the json to be not equal, the problem is that I cannot modify the server because other platforms use the same API. 

I have attach two JSON adding comments (inside) to  explain the relationships between classes.


1º JSON to download an "User Group"

```

{
	"meta": {
		"limit": 1,
		"next": "/api/v1/group/?limit=1&offset=1",
		"offset": 0,
		"previous": null,
		"total_count": 5
	},
	“//”: “Class User Group,
	"objects": [{
		"creation_date": "2018-01-25T04:54:51.875560",
		"deleted": false,
		"description": "Development",
		"group_logo": "//s3.amazonaws.com/prod_pm_avatars/companylogos/None/nerd.jpg",
		"id": 3,
		"is_private": false,
		“//”: “Class User Group Membership,
		"memberships": [
			{
				"id": 13,
				"joined_date": "2018-01-25T04:54:51.886031",
				"role": 0,
				"user": {
					"date_joined": "2012-05-13T00:00:00",
					"email": "x@xxx.com",
					"first_name": "xxx",
					"full_name": "xxx",
					"id": 3015,
					"last_login": "2018-05-17T07:11:02.507537",
					"last_name": "xxx",
					"resource_uri": "/api/v1/user/3015/",
					"teammate": true,
					"user_profile": "/api/v1/user_profile/3010/",
					"username": "x@xxx.com"
				}
			}
		],
		"name": "Development",
		"resource_uri": "/api/v1/group/3/"
	}]
}

```

2º JSON to download an project with identifier for "User Group" and "User Project Membership" relationship

```
{
	"meta": {
		"limit": 1,
		"next": "/api/v1/project/?returnmemberships=1&limit=1&offset=1",
		"offset": 0,
		"previous": null,
		"requested_time": 1527601157,
		"server_time": 1527601388.59648,
		"total_count": 374
	},
	“//”: “Class Project”,
	"objects": [{ 
		"account_uri": null,
		"boxFolderID": null,
		"colorFirstQuadrant": "{0.598001, 0.598001, 0.598001, 1}",
		"colorFourthQuadrant": "{0.897002, 0.897002, 0.897002, 1}",
		"colorSecondQuadrant": "{0.929, 0.592004, 0.792004, 1}",
		"colorThirdQuadrant": "{0.796994, 0.796994, 0.796994, 1}",
		"completed_effort": 0,
		"creationDate": 1508499701,
		"creator": "/api/v1/user/3015/",
		"creator_username": "x2@xxx.com",
		"editedByDevice": "095ab868ba38142dc1da1130e777d2c4491336bb",
		"edited_by_username": "x3@xxx.com",
		"endDate": null,
		"hash": "",
		"idd": 161850,
		"is_team_project": false,
		“//”: “Class User Project Membership”,
                “//”: “This relationship is confusing with memberships relationship of  User Group class”,
		"memberships": [
			{
				"created_date": "1526540822",
				"deleted": false,
				"following": false,
				"id": 511751,
				"item_role": 2,
				"project": "/api/v1/project/161850/",
				"project_role": 2,
				"timestamp": "1526540822",
				"user": "/api/v1/user/14/",
				"username": "x@xxx.com"
			}
		],
		"name": "Backend",
		"notes": "",
		"owner": [
			"/api/v1/user/14/"
		],
		"owners_count": 11,
		"requested_time": 1527601388.59398,
		"resource_uri": "/api/v1/project/161850/",
		"startDate": null,
		"state": 0,
		“//”: ““Class Tag”,
		"tags": [{
				"id": 6824,
				"name": "sync",
				"resource_uri": "/api/v1/tag/6824/",
				"slug": "sync"
			}
		],
		"templateCreationDate": null,
		"textFirstQuadrant": "P1 - Fires",
		"textFourthQuadrant": "Uncategorized",
		"textSecondQuadrant": "P2 - Planned",
		"textThirdQuadrant": "P3 - Low Priority",
		"timestamp": 1527601157,
		"total_effort": 0,
		“//”: “Identifier for Class User Group",
		"user_group_id": 3,
		"version_id": 75180771
	}]
}
```

**Comment by dimazen** [comment]
@asam139 ok, now your issues looks a lot clearer. Issue lies in a mapping that actually combines simple PK binding and actual mapping. There are few things to consider: 
- it is ok to create many mappings
- it is ok to create mapping at every call.

What actually goes wrong in your case is that by specifying 
```
FEMRelationship *userGroupRelationship = [[FEMRelationship alloc] initWithProperty:@"userGroup" keyPath:nil mapping:UserGroup.defaultMappingRelationshipByPK];
userGroupRelationship.weak = YES;
[mapping addRelationship:userGroupRelationship];
```
you actually pass a mapping for a _full_ object which is obviously not the case. 
Now, let me show you an update version:

For class project:
```
+ (FEMMapping *)defaultMapping {
  FEMMapping *mapping = [[FEMMapping alloc] initWithEntityName:NSStringFromClass(self.class)];
  // description of the attributes

  // binding of the user group
  
  FEMMapping *userGroupMapping = [[FEMMapping alloc] initWithEntityName:NSStringFromClass(UserGroup.class)];
  userGroupMapping.primaryKey = @"serverID";
  [userGroupMapping addAttributesFromDictionary:@{@"serverID": @"user_group_id"}];
  FEMRelationship *userGroupRelationship = [[FEMRelationship alloc] initWithProperty:@"userGroup" keyPath:nil mapping:userGroupMapping];
  userGroupRelationship.weak = YES;
  [mapping addRelationship:userGroupRelationship];

  return mapping;
```

Ok, so what have changed? Now we're simply mapping only a primary key and not touching anything else. Therefore you won't fall into a case where user group tries to map membership from a class. 

Hope this will resolve your issue.

**Comment by dimazen** [comment]
Just to add: during PK binding you can actually specify only a primary key (and any required fields), you don't have to pass a full description of the object.

**Comment by asam139** [comment]
Thanks so much. It works perfectly, I did not know that it is not necessary to specify the full description. I apologize for the inconvenience.
