### ISSUE TITLE
getting error in mapping 

### ISSUE THREAD

**Issue by krishnasolankiBigbang** [Yalantis/FastEasyMapping#123]
Hello 
I am using swift verison pod 'FastEasyMapping', '~> 1.2'. 
I am getting error desired type = NSOrderedSet; given type = __NSArrayM
Getting exception in line mapping.addToManyRelationshipMapping(ABC.defaultmapping(), forProperty: "cde", keyPath: "CDE")
property of cde is in  ABC is 
@NSManaged var cde : NSOrderedSet!

**Comment by dimazen** [comment]
@krishnasolankiBigbang good day!
Sorry for a long delay.
Can you share your mapping, please?

**Comment by krishnasolankiBigbang** [comment]
Hello @dimazen  Its hase been Solved issue was my side it was silly mistake . I set mapping.addToManyRelationshipMapping(ABC.defaultmapping(), forProperty: "cde", keyPath: "CDE")
But from API key name was cde , But Currently getting new issue ::
https://github.com/Yalantis/FastEasyMapping/issues/124
Thanks .
