### ISSUE TITLE
Can not map attribute from string to Double

### ISSUE THREAD

**Issue by krishnasolankiBigbang** [Yalantis/FastEasyMapping#125]
Hello 
I am getting response lattitude value as String ,In database its double value. Though there is some value from server,  I am getting 0 value everytime.Code is as bellow :: 

@NSManaged var lattitude : Double
 class func defaultmapping()->FEMMapping{
mapping.addAttribute(Mapping.doubleAttributeFor(property: "lattitude" , keyPath: "Lattitude"))
}

File :: Mapping.swift

class func doubleAttributeFor(property:String,keyPath:String)->FEMAttribute{
        let atr = FEMAttribute.init(property: property, keyPath: keyPath, map: { (valueInt) -> Double? in

            if(type(of: valueInt) == String.Type.self){

                return NSNumber.init(value: Double(valueInt as? String ?? "0.00") ?? 0.00000) as? Double
            }
            return valueInt as? Double
        }, reverseMap: { (valueInt) -> Any? in

            return String(format: "%.02f", arguments: [Double(valueInt as? String ?? "0.00") ?? 0.00000])
        })
        return atr
    }

**Comment by dimazen** [comment]
How about that:
```
FEMAttribute(property: "", keyPath: "", map: { value -> Any? in
			if let value = value as? String, let convertedValue = Double(value) {
				return NSNumber(value: convertedValue)
			}
			return nil
		}, reverseMap: { value -> Any? in
			if let value = value as? NSNumber {
				return value.stringValue
			}
			return nil
		}
```
?

**Comment by krishnasolankiBigbang** [comment]
App is getting crash with exception ::
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: property.length > 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e26b27e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000010deeeb20 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e26aff8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x000000010ca56b51 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   FastEasyMapping                     0x000000010c9f4076 -[FEMAttribute initWithProperty:keyPath:map:reverseMap:] + 422
	5   SuperSales                          0x0000000108531183 $sSo12FEMAttributeC8property7keyPath3map10reverseMapABSS_SSSgypSgAHcSgAItcfcTO + 611
	6   SuperSales                          0x000000010852e2e4 $sSo12FEMAttributeC8property7keyPath3map10reverseMapABSS_SSSgypSgAHcSgAItcfC + 116
	7   SuperSales                          0x000000010852ecf8 $s10SuperSales7MappingC18doubleAttributeFor8property7keyPathSo12FEMAttributeCSS_SStFZ + 200
	8   SuperSales                          0x0000000107d2f328 $s10SuperSales7ContactC14defaultMappingSo10FEMMappingCyFZ + 1240
	9   SuperSales                          0x000000010874d7de $s10SuperSales9ApiHelperC13getAllContact10completionyyyp6result_SS6statusSS7messageSo7NSErrorC5errorAA12ResponseTypeO08responseO0t_tc_tFyyp_S2SAjMtcfU_ySo22NSManagedObjectContextCcfU_Tf2ni_n + 222
	10  SuperSales                          0x0000000107e136e6 $sSo22NSManagedObjectContextCIegg_ABIeyBy_TR + 70
	11  MagicalRecord                       0x000000010d8424f3 __51+[MagicalRecord(Actions) saveWithBlock:completion:]_block_invoke + 131
	12  CoreData                            0x000000010b1d7e36 developerSubmittedBlockToNSManagedObjectContextPerform + 154
	13  libdispatch.dylib                   0x000000010f5a9d48 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010f5b05ef _dispatch_lane_serial_drain + 788
	15  libdispatch.dylib                   0x000000010f5b117f _dispatch_lane_invoke + 422
	16  libdispatch.dylib                   0x000000010f5bca4e _dispatch_workloop_worker_thread + 719
	17  libsystem_pthread.dylib             0x000000010faeb611 _pthread_wqthread + 421
	18  libsystem_pthread.dylib             0x000000010faeb3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by krishnasolankiBigbang** [comment]
xxx is my app name , App is getting crash with this exception ::
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: property.length > 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109a9627e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x0000000109719b20 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109a95ff8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00000001082d3b51 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   FastEasyMapping                     0x0000000106bed076 -[FEMAttribute initWithProperty:keyPath:map:reverseMap:] + 422
	5 xxx                          0x0000000103c88173 $sSo12FEMAttributeC8property7keyPath3map10reverseMapABSS_SSSgypSgAHcSgAItcfcTO + 611
	6  xxx                          0x0000000103c850a4 $sSo12FEMAttributeC8property7keyPath3map10reverseMapABSS_SSSgypSgAHcSgAItcfC + 116
	7   xxx                          0x0000000103c85ce2 $s10SuperSales7MappingC18doubleAttributeFor8property7keyPathSo12FEMAttributeCSS_SStFZ + 754
	8   xxx                          0x00000001034860e8 $s10SuperSales7ContactC14defaultMappingSo10FEMMappingCyFZ + 1240
	9   xxx                          0x0000000103ea47ce $s10xxx9ApiHelperC13getAllContact10completionyyyp6result_SS6statusSS7messageSo7NSErrorC5errorAA12ResponseTypeO08responseO0t_tc_tFyyp_S2SAjMtcfU_ySo22NSManagedObjectContextCcfU_Tf2ni_n + 222
	10  xxx                          0x000000010356a4a6 $sSo22NSManagedObjectContextCIegg_ABIeyBy_TR + 70
	11  MagicalRecord                       0x00000001090744f3 __51+[MagicalRecord(Actions) saveWithBlock:completion:]_block_invoke + 131
	12  CoreData                            0x0000000106d98e36 developerSubmittedBlockToNSManagedObjectContextPerform + 154
	13  libdispatch.dylib                   0x000000010add4d48 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010addb5ef _dispatch_lane_serial_drain + 788
	15  libdispatch.dylib                   0x000000010addc17f _dispatch_lane_invoke + 422
	16  libdispatch.dylib                   0x000000010ade7a4e _dispatch_workloop_worker_thread + 719
	17  libsystem_pthread.dylib             0x000000010b23e611 _pthread_wqthread + 421
	18  libsystem_pthread.dylib             0x000000010b23e3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dimazen** [comment]
Ok, it seems, that you have passed an empty property. Can you share your code, please?

**Comment by dimazen** [comment]
The code I've posted above is just a sample one, you need to pass property and keypath over there

**Comment by krishnasolankiBigbang** [comment]
Ya , It Was my mistake particular property type was different . Your code worked.

Thanks   a lot.
