### ISSUE TITLE
How to map double value in Swift 

### ISSUE THREAD

**Issue by krishnasolankiBigbang** [Yalantis/FastEasyMapping#128]
Hello ,

I am using femmapping in swift.I need guidance for mapping double value .My code is as bellow.

"//For Product Class
     let atr = FEMAttribute(property: property, keyPath: keyPath, map: { value -> Any? in
            
            if let value = value as? String, let convertedValue = Double(value) {
                return NSNumber(value: convertedValue)
            }
            return nil
        }, reverseMap: { value -> Any? in
            if let value = value as? NSNumber {
                return value.stringValue
            }
            return nil
        })
        return atr 
        
        // For Customer class 
      let atr = FEMAttribute.init(property: property, keyPath: keyPath, map: { (valueInt) -> Double? in
 
            if(type(of: valueInt) == String.Type.self){

                return NSNumber.init(value: Double(valueInt as? String ?? "0.00") ?? 0.00000) as? Double
            }
            return valueInt as? Double
        }, reverseMap: { (valueInt) -> Any? in

return String(format: "%.02f", arguments: [Double(valueInt as? String ?? "0.00") ?? 0.00000])
        })
        return atr"
if i am kepping first portion in second class functionality  stopped  working , same way if I am using second  portion  in first class functionality  stopped  working

**Comment by dimazen** [comment]
Hello, @krishnasolankiBigbang 
First code looks pretty solid. I would do the same unless there are more things. Can you tell me what exactly goes wrong? Are you using the same attribute across different mappings?

**Comment by krishnasolankiBigbang** [comment]
Sorry for late , Its Solved Actually  issue was due to  backend side , as in one class value was coming in string and I Aspect as float So this happened .
