### ISSUE TITLE
Support for same class nested objects ? 

### ISSUE THREAD

**Issue by nashfive** [Yalantis/FastEasyMapping#23]
I am trying to use FastEasyMapping to support nested objects of the same type.

For example, a class Person might have an array of Person (children...) : 
```objective-c
@interface Person:NSObject
@property (nonatomic, strong) NSString *name;
@property (nonatomic, strong) NSArray *children;
@end

+ (FEMObjectMapping *)personMapping {
    return [FEMObjectMapping mappingForClass:Person.class configuration:^(FEMObjectMapping *mapping) {
        [mapping addAttributesFromArray:@[@"name"]];
        [mapping addToManyRelationshipMapping:self.personMapping forProperty:@"children" keyPath:@"children"];
    }];
}
```

This obviously ends up in an infinite loop... 

Is there a way to use FastEasyMapping with this setup ?

**Comment by dimazen** [comment]
@nashfive 
Every person (even nested one) can have children, correct? No limits for nesting?

**Comment by nashfive** [comment]
@dimazen Exactly. Sorry I forgot to mention the "unlimited" nesting levels...

**Comment by dimazen** [comment]
@nashfive 
Well, fem not designed for stuff like that. However, you can try kind of a workaround like that:

```
+ (FEMObjectMapping *)personMapping {
    FEMObjectMapping *mapping = [[FEMObjectMapping alloc] initWithObjectClass:self];

    [mapping addAttributesFromArray:@[@"name"]];
    
    FEMRelationship *children = [[FEMRelationship alloc] initWithProperty:@"children" keyPath:@"children" assignmentPolicy:FEMAssignmentPolicyAssign objectMapping:mapping];
    children.toMany = YES;
    [mapping addRelationship:children];

    return mapping;
}
```

To be honest, I'm not sure, but it *might* work.

**Comment by dimazen** [comment]
@nashfive 
You have to note, that there is a retain cycle as well.

**Comment by nashfive** [comment]
@dimazen 
Thanks... It works, but as you mentioned, it also creates retain cycles... 
By the way, I am closing the issue because I was just evaluating JSON parsers ;-)

Thanks again for your help.

**Comment by dimazen** [comment]
@nashfive you're welcome!
