### ISSUE TITLE
Best way to track changes

### ISSUE THREAD

**Issue by k06a** [Yalantis/FastEasyMapping#28]
I am using CoreData and trying to track when my entity field `logo_url` is changed so I can download new logo right after entities updating finished. I there any less code solution other then remembering old values before updating and comparing them with new values?

**Comment by k06a** [comment]
Maybe to store Photo on separate entity and update relationship after changing? But how my mapping should look like this way? It is just:
```
...
"logo_url" : "http://.../image.jpg"
...
```

**Comment by dimazen** [comment]
Hello, @k06a 
Hm, I'm thinking on adding some kind of "post-actions". They looks like 

class Actions {
   .. onObjectMapping (object, representation) 
}

However, your #30 can be possible way out, I'll take a detail look on this weekends

**Comment by dimazen** [comment]
@k06a If this issue still relevant check out branch https://github.com/Yalantis/FastEasyMapping/tree/1.0
It behaves identically. What you're looking for is a FEMDeserializerDelegate, which allows you to do next 
```swift
    func deserializer(
        deserializer: FEMDeserializer!,
        didMapObject object: AnyObject!,
        fromRepresentation representation: [NSObject : AnyObject]!,
        mapping: FEMMapping!
    ) {
        if objectsMapping.entityName == mapping.entityName {
            postObjectMappingAction?(object)
        }
    }
```

All you needs to be aware of is: ```FEMManagedObjectMapping``` & ```FEMObjectMapping``` are now combined into ```FEMMapping```, ```FEMManagedObjectDeserializer``` & ```FEMObjectDeserializer``` are now represented by ```FEMDeserializer```.

Most of the methods are now shorter, however you can update it for free - deprecated methods supported as well. 

```objective-c
// old
+ (id)deserializeObjectExternalRepresentation:(NSDictionary *)externalRepresentation usingMapping:(FEMMapping *)mapping;

// new
+ (id)objectFromRepresentation:(NSDictionary *)representation mapping:(FEMMapping *)mapping;

// old
+ (NSArray *)deserializeCollectionExternalRepresentation:(NSArray *)externalRepresentation usingMapping:(FEMMapping *)mapping context:(NSManagedObjectContext *)context;

// new
+ (NSArray *)collectionFromRepresentation:(NSArray *)representation mapping:(FEMMapping *)mapping context:(NSManagedObjectContext *)context;
```

**Comment by dimazen** [comment]
So in your specific case you have to use next code: 

```objective-c
FEMObjectStore *store = [[FEMManagedObjectStore alloc] initWithContext:[NSManagedObjectContext MR_defaultContext]];
FEMDeserializer *deserializer = [[FEMDeserializer alloc] initWithStore:store];
deserializer.delegate = self;
NSArray *objects = deserializer.collectionFromRepresentation(objects, mapping: objectsMapping)
```

**Comment by dimazen** [comment]
Then by implementing ```FEMDeserializedDelegate``` you can receive most of the deserailziation callbacks. Be aware that in those callbacks you'll receive not only top-level entities, but entities from relationship as well, so check FEMMapping.entityName to be sure.

**Comment by k06a** [comment]
It will be perfect to see updated `readme.md` on new branch `1.0`

**Comment by k06a** [comment]
I think tracking changes is very helpful on object side. Like I did it here: https://github.com/Yalantis/FastEasyMapping/pull/30

I am really disappointed that method `[NSManagedObject didChangeValueForKey:]` is denied to be overrriden:
```
Invoked to inform the receiver that the value of a given property has changed.
For more details, see Key-Value Observing Programming Guide.
You must not override this method.
```

**Comment by dimazen** [comment]
@k06a I'm going to roll out 1.0 on this weekends, so you should be able to track at least mapping progress itself, not the changes. 

changed values can be tracked in ```willSave```.

**Comment by dimazen** [comment]
@k06a Version [1.0](https://github.com/Yalantis/FastEasyMapping/releases/tag/1.0) is released! You can check [Delegation](https://github.com/Yalantis/FastEasyMapping#delegation) section for docs.
