### ISSUE TITLE
addRelationshipMapping issue

### ISSUE THREAD

**Issue by DenisDbv** [Yalantis/FastEasyMapping#29]
I have user entity in card entity. Card have relation to user. 1-1
{
  "user": {
       "phone": "11111111111",
        "active": true
    }

  ....
}

In Card mapping:
[mapping addRelationshipMapping:[User mapObject]
                                                                         forProperty:@"creator"
                                                                             keyPath:@"user"];

In Card manager:
FEMManagedObjectMapping *mapping = [Card cardMapping];
                [FEMManagedObjectDeserializer fillObject:card fromExternalRepresentation:cardDict usingMapping:mapping];

Show next issue:
-[User count]: unrecognized selector sent to instance 0x7fa863d49680
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[User count]: unrecognized selector sent to instance 0x7fa863d49680'

*** First throw call stack:
(
	0   CoreFoundation                      0x000000010998ff35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001092cdbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010999704d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00000001098ef27c ___forwarding___ + 988
	4   CoreFoundation                      0x00000001098eee18 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00000001098e9bee +[NSSet setWithArray:] + 46
	6   Welpy                               0x00000001047d9d73 +[FEMManagedObjectDeserializer _fillObject:fromRepresentation:usingMapping:] + 2595
	7   ---                               0x00000001047da151 +[FEMManagedObjectDeserializer fillObject:fromExternalRepresentation:usingMapping:] + 321
	8   ---                               0x00000001046e4b50 __37-[CardsManager saveCards:completion:]_block_invoke + 960
	9   ---                               0x0000000104a3771a __51+[MagicalRecord(Actions) saveWithBlock:completion:]_block_invoke + 58
	10  CoreData                            0x0000000105c96f06 developerSubmittedBlockToNSManagedObjectContextPerform + 198
	11  libdispatch.dylib                   0x000000010a0ea7f4 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010a0d2b22 _dispatch_queue_drain + 1417
	13  libdispatch.dylib                   0x000000010a0d2432 _dispatch_queue_invoke + 235
	14  libdispatch.dylib                   0x000000010a0d4fc1 _dispatch_root_queue_drain + 685
	15  libdispatch.dylib                   0x000000010a0d6612 _dispatch_worker_thread2 + 52
	16  libsystem_pthread.dylib             0x000000010a482ef8 _pthread_wqthread + 314
	17  libsystem_pthread.dylib             0x000000010a485fb9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dimazen** [comment]
@DenisDbv Can you post description of how both Card and User mapping as well as full json?
