### ISSUE TITLE
Hi! In the future will add a detailed use the Demo?

### ISSUE THREAD

**Issue by xhzengAIB** [Yalantis/FastEasyMapping#34]

**Comment by dimazen** [comment]
@xhzengAIB 
Unfortunately, I'm releasing project atm, so can't tell you exactly about terms of the update. 100% it'll be updated with 1.0 release (https://github.com/Yalantis/FastEasyMapping/tree/1.0)

**Comment by xhzengAIB** [comment]
Hi! @dimazen 

Convert NSObject model, need complete encodeWithCoder: and initWithCoder: methods?

Jack

**Comment by xhzengAIB** [comment]
I check the Mantle, subClasse MTLModel don't need to implement encodeWithCoder: and initWithCoder: methods

**Comment by dimazen** [comment]
@xhzengAIB I've released [1.0](https://github.com/Yalantis/FastEasyMapping/releases/tag/1.0) version with updated README, that contains most of the info you need. Also tests was update to the latest syntax, so you can use them as an example.

**Comment by xhzengAIB** [comment]
@dimazen 
Thank you！
