### ISSUE TITLE
is CoreData required?

### ISSUE THREAD

**Issue by steve21124** [Yalantis/FastEasyMapping#35]
Easy mapping does not need core data. Is it correct to assume FastEasyMapping does not require coredata?
https://github.com/EasyMapping/EasyMapping

**Comment by dimazen** [comment]
No, you can map plain old NSObject ;) Just use `FEMMapping *mapping = [[FEMMapping alloc] initWithObjectClass:];`

**Comment by steve21124** [comment]
thanks. I just read from your article "In order to import data from JSON to Core Data". Good thing you mentioned it did not require CoreData. just from quick skim through, I thought it require CoreData.

**Comment by steve21124** [comment]
by the way, FastEasyMapping created for CoreData in mind. (https://yalantis.com/blog/from-json-to-core-data-fast-and-effectively/) If I am not using CoreData, will I have the benefit of fast performance compare to EasyMapping? or only if I use CoreData then I get the benefit of fast performance?

**Comment by dimazen** [comment]
Actually there should be almost no difference, since EasyMapping merged our performance improvements, so if you already using EM, there is no real reason to move to the FEM in terms of performance. ;)

**Comment by steve21124** [comment]
ooo. good. thanks for the clarification. that's save me a lot of time in testing it.

**Comment by dimazen** [comment]
You're welcome!
