### ISSUE TITLE
Is there any JSON Mapping faster than FastEasyMapping?

### ISSUE THREAD

**Issue by steve21124** [Yalantis/FastEasyMapping#36]
I have 100k rows of data with 100 fields. I have integrate EasyMapping and it takes about 8 seconds to map it to object class. Since FastEasyMapping created for performance issue, do you know any other ways to even improve the mapping performance?

**Comment by dimazen** [comment]
Can you share a time profiler data? (via skype or drop link here)

**Comment by dimazen** [comment]
If this time includes saving of data then you can try to split your data into chunks and import by 1k for example. And measure, what's working best for you.

**Comment by steve21124** [comment]
Thank you for the help and good idea into splitting into chunks. The performance improvement currently targeting time to do data mapping.

Here is the sample JSON Data
https://www.dropbox.com/s/zpxjl5wsjfpe2sm/JSONData.json.zip?dl=0
and using EasyMapping test code. 
https://www.dropbox.com/s/dff082mtj1jd1ny/EasyMapping.zip?dl=0

you can execute the command using this and it take about 8 - 10 seconds
[[SCTestEasyMappingArrayController sharedInstance] parseUsingSCTestEasyMappingArray];

**Comment by steve21124** [comment]
oh yeah, if swift be able to improve the performance, that's totally fine too.

**Comment by dimazen** [comment]
@steve21124 
Ok, it seems, that we're dealing with KVC & ARC constraints. I don't see any way (for now) that can dramatically improve performance. 

About Swift: I don't believe it'll improve performance. Rather the contrary.

**Comment by steve21124** [comment]
Thanks @dimazen. yes, KVC alternative will be Fast enumeration however it will be less flexible. Do you know by any chance, know the Time Complexity of KVC (Big-O) under the hood?

**Comment by dimazen** [comment]
Have no idea. I'm pretty sure, that KVC is quite optimized. 
All you can do, probably, is to switch to the C and direct ```object.value = dictionary.objectForKey(...)```
This will eliminate KVC layer and save some time ;)

**Comment by steve21124** [comment]
Thanks @dimazen. I agree. I will close the issue for now. I think we are at the point of no dramatically optimization improvement can be done as far as requirement of only using ObjectiveC/Swift
