### ISSUE TITLE
Get current context in mapping

### ISSUE THREAD

**Issue by sxua** [Yalantis/FastEasyMapping#37]
Is it possible to get a current context in mapping in 1.0 like it was before with `FEMCacheGetCurrent()`?
Or maybe there's some other workaround exists for such cases?

```objc
[mapping addAttribute:[FEMAttributeMapping mappingOfProperty:@"client" toKeyPath:@"client.id" map:^id(id value) {
    return [Client MR_findFirstByAttribute:@"external_id" withValue:value inContext:[FEMCacheGetCurrent() context]];
}]];
```

**Comment by dimazen** [comment]
@sxua 
It seems, that you should be using [relationship](https://github.com/Yalantis/FastEasyMapping#relationship-bindings-by-pk) binding instead of manual lookup ;)

**Comment by sxua** [comment]
@dimazen Sometimes you have to deal with existing API and mobile app database structure. That's why I'm still using FEM v0.5.1. :-)

**Comment by dimazen** [comment]
You can use the same approach for 0.5.1 for relationships: 

```
+ (FEMMapping *)defaultMapping {
    FEMManagedObjectMapping *mapping = [[FEMManagedObjectMapping alloc] initWithEntityName:@"MainEntity"];
    mapping.primaryKey = @"identifier";
    [mapping addAttributesFromDictionary:@{@"identifier": @"id"}];

    FEMManagedObjectMapping *clientMapping = [[FEMManagedObjectMapping alloc] initWithEntityName:@"Client"];
    categoryMapping.primaryKey = @"external_id";
    [categoryMapping addAttributesFromDictionary:@{@"external_id": @"id"}];

    [mapping addRelationshipMapping:categoryMapping property:@"client" keyPath:@"client"];

    return mapping;
}
```

**Comment by sxua** [comment]
Ok, thanks. Looks promising. :+1:

**Comment by dimazen** [comment]
@sxua by the way, 1.0 is backward compatible with 0.5.1 via `@compatilibity_alias`. So after update you'll be able to use the same syntax as before just with couple of warnings.
