### ISSUE TITLE
Reference to ‘FEMManagedObjectMapping’ is ambiguous

### ISSUE THREAD

**Issue by arietis** [Yalantis/FastEasyMapping#45]
Hello!
I’m getting error “Reference to ‘FEMManagedObjectMapping’ is ambiguous” when building my project using version 1.0.1. Version 0.5.1 i have used before works fine. Any ideas what am i doing wrong?
Thanks!

**Comment by dimazen** [comment]
Hm.. Quite strange error. In 1.0  `FEMManagedObjectMapping` has been renamed to the `FEMMapping`. I've added typealias for such migration, however it doesn't work for you :( 

Ugly way to fix it is to replace `FEMManagedObjectMapping` by `FEMMapping`.

**Comment by arietis** [comment]
I still have the issue after replacement.

**Comment by dimazen** [comment]
@arietis Finally I've fixed it. Checkout 1.0.2 release!
