### ISSUE TITLE
Use of '@import' when modules are disabled

### ISSUE THREAD

**Issue by schwindt** [Yalantis/FastEasyMapping#47]
Installed with cocoapods 
added FEMMappingUtility.h to the project pch file and get:
FEMMappingUtility.h:6:1: Use of '@import' when modules are disabled

**Comment by dimazen** [comment]
This is due to the `@import` usage instead of plain `#import ""`. 
There are two ways: 
1. enable modules in your project
2. I'll replace @import by #import if possible

**Comment by dimazen** [comment]
Fixed by unexpected @import statement in FEMMappingUtility in 1.1
