### ISSUE TITLE
Any plans for Realm support?

### ISSUE THREAD

**Issue by mmartikainen** [Yalantis/FastEasyMapping#49]
I am interested in using FEM with Realm.
Any plans on implementing a FEMRealmObjectStore?

**Comment by dimazen** [comment]
Hello, @mmartikainen. Actually, there is an implementation of that store in the branch [feature/realm](https://github.com/Yalantis/FastEasyMapping/tree/feature/realm). But I'm quite busy for this moment to finish it :(

**Comment by dimazen** [comment]
I believe this is not relevant anymore but just for convenience: Realm support finally here: 
https://github.com/Yalantis/FastEasyMappingRealm
