### ISSUE TITLE
Ability to disable autocreation properties

### ISSUE THREAD

**Issue by fedser** [Yalantis/FastEasyMapping#50]
Now each property/relationship autocreated even if there are missing such json key in response. For relationship there are exists similar option like "weak", but it's has another meaning.
Could you add in mapping property like "disableAutocreation" to exclude creation empty object if there are missing key in json(during looking in the  code is should involve on "allocateIfNeeded" in FEMDeserializer). Also as additional option I could use "map:".

**Comment by dimazen** [comment]
Hello, @fedser. 
Could you please share an example of the JSON and mapping for me to better understand (few fields will be more than enough). As far as I understood, you want to skip creation of the instance if one of the keys is not presented?

**Comment by fedser** [comment]
Here are example of part json:
`{"result":[{"id":"234242342","name":"Pack 9","rightContactLensArticle":{"type":"ContactLens","productName":"Product 1","lifecycleState":"Active","supplierDeliveryTime":1440,"storageType":"None","isDeliverable":false,"package":{"size":3,"unit":"Pieces"},"price":{"currency":"EUR","grossAmount":12.59},"id":"22222222"},"rightOpticalSpecification":{"diameter":14,"radiusBaseCurve":8.6,"sphere":-4,"addition":1},"activatedForOnline":true,"createdAt":"2015-01-01T09:09:27.7690000Z"}
]}`

In "result" there list of ContactLensInfo. Please notice that now in json we receive "rightContactLensArticle", but also we could receive "leftContactLensArticle". Problem is that I always have not nil property leftArticleWithOpticalParams in model (but properties of leftArticleWithOpticalParams are nil).
Here are header of ContactLensInfo:
`@interface ContactLensInfo : NSObject`
`@property (nonatomic, strong) NSString *modelID;`
`@property (nonatomic, strong) NSString *name;`
`@ property (nonatomic, strong) FLContactLensArticleWithOpticalParams *leftArticleWithOpticalParams;`
`@property (nonatomic, strong) FLContactLensArticleWithOpticalParams *rightArticleWithOpticalParams;`
`@property (nonatomic, strong) NSNumber *activatedForOnline;`
`@end`

Here are how mapping occurs on root level:
`+ (FEMMapping *)defaultMapping {`
`    FEMMapping *mapping = [[FEMMapping alloc] initWithObjectClass:self.class];`
`    [mapping addAttributesFromArray:@[@"activatedForOnline", @"name"]];`
`    [mapping addAttributesFromDictionary:@{@"modelID": @"id"}];`
`    FEMMapping *leftArticleMapping = [FLContactLensArticleWithOpticalParams defaultMappingWithArticleKeyPath:@"leftContactLensArticle" opticalParamsKeyPath:@"leftOpticalSpecification"];`
`    FEMRelationship *leftRS = [[FEMRelationship alloc] initWithProperty:@"leftArticleWithOpticalParams" mapping:leftArticleMapping];`
`    [mapping addRelationship:leftRS];`
    
`    FEMMapping *rightArticleMapping = [FLContactLensArticleWithOpticalParams defaultMappingWithArticleKeyPath:@"rightContactLensArticle" opticalParamsKeyPath:@"rightOpticalSpecification"];`
`    FEMRelationship *rightRS = [[FEMRelationship alloc] initWithProperty:@"rightArticleWithOpticalParams" mapping:rightArticleMapping];
    [mapping addRelationship:rightRS];`
`    return mapping;`
`}`

**Comment by dimazen** [comment]
Sorry, was highly busy. It seems, I got what you're talking about. 
From what I see you need to set ```keyPath``` to the relationship itself, not to the ```leftArticleMapping``` . It is a bit confusing, but the issue here is that during relationship parsing deserializer takes your relationship, sees that there is no ```keyPath``` and uses the whole object representation. Therefore it thinks that object exists, while it is not.

**Comment by fedser** [comment]
Ok, I see what you mean and your first reply in this thread was correct but I misunderstood it while. Yes, I need more like "mandatory keys" for my case, but in this case library will be more complex. Thanks!
