### ISSUE TITLE
How do you parse ?

### ISSUE THREAD

**Issue by LivioGama** [Yalantis/FastEasyMapping#52]
Hi,

How would you parse : 
```json
{
    "uuid": "bbb",
    "comment": "Hi hello",
    "username": "Alex",
    "likers_uuids": ["xxx", "yyy", "zzz"],
    "post_uuid: "hhh"
}
```

Comment.swift
```swift
class Comment: BaseObject {
    var username:String
    var commentDescription: String
    var likers: [User]
    var post: Post

    override class func defaultMapping() -> FEMMapping {
        let mapping = super.defaultMapping() // parsing uuid in super class

        mapping.addAttributesFromDictionary(["commentDescription": "comment"])

     // Line below is wrong because likers_uuids  doesn't deliver an object {"uuid" : "ggg", "username": "Patrick"} put directly an array of String containing uuids
        mapping.addToManyRelationshipMapping(User.defaultMapping(), forProperty: "likers", keyPath: "likes_uuids")
    // Neither this one because post_uuid doesn't deliver an object {"uuid": "eee", "create_date": 12345} but the uuid of the post to relate to
        mapping.addToManyRelationshipMapping(Post.defaultMapping(), forProperty: "post", keyPath: "post_uuid")
        return mapping
    }
}
```

**Comment by dimazen** [comment]
Hello, @LivioGama. Sorry for a big delay. Looks like you need to setup a relationship based on a primary key, so this is how I would go: 

```
class func defaultMapping() -> FEMMapping {
    let mapping = FEMMapping(entityName: "Comment")
    mapping.primaryKey = "uuid"
    mapping.addAttributesFromDictionary(["uuid": "uuid", "commentDescription": "comment"])

    let user = FEMMapping(entityName: "User")
    user.primaryKey = "uuid"
    user.addAttributeWithProperty("uuid", keyPath: nil)
    
    let userRelationship = FEMRelationship(property: "likers", keyPath: "likers_uuids", mapping: user)
    userRelationship.toMany = true
    userRelationship.weak = true
    
    mapping.addRelationship(userRelationship)
    
    let post = FEMMapping(entityName: "Post")
    post.primaryKey = "uuid"
    post.addAttributeWithProperty("uuid", keyPath: nil)
    
    let postRelationship = FEMRelationship(property: "post", keyPath: "post_uuid", mapping: post)
    postRelationship.weak = true
    mapping.addRelationship(postRelationship)
    
    return mapping
}
```

You can notice a trick, when we're adding the ```uuid``` attribute at ```nil``` keyPath. It leads to the case when deserializer use whole object representation as a value for the ```uuid```. In other words it goes like that: 

* map attributes for ```Comment```
* map relationships for ```Comment```:
  * get representation of the ```Post``` relationship: it is a ```String```. 
  * map first (and the only) attribute of the post: ```uuid```. It has nil ```keyPath``` so we're simply use this value (uuid's string) as actual ```uuid```. 
  * so on...

**Comment by LivioGama** [comment]
Thanks for the answer ! I did it another way during this time and it works too :
<pre><code>
 let comment = FEMDeserializer.objectFromRepresentation(commentJSON.dictionaryObject!, mapping: Comment.defaultMapping(), context: context) as! Comment
        let postId = commentJSON["post_id"].stringValue
        let post = FEMDeserializer.objectFromRepresentation(["uuid": postId], mapping: Post.defaultMapping(), context: context) as! Post

        comment.post = post
</code></pre>
Which is doing it, but from the object external point of view while parsing, instead of inner mapping in the object and it works like a charm too !

Your tool is simply great! I was being desperate with bad performance of CoreData, I was parsing a User with 500 followers which were themselves users to create by uuid, and getting 12 seconds of frozen UI.
 With FEM everything take 0 second and the app is just perfectly smooth, I love it, I want to put it in all my projects !
