### ISSUE TITLE
Mapping ISO Date

### ISSUE THREAD

**Issue by Chhaya** [Yalantis/FastEasyMapping#58]
Hello, 
I am having problem with mapping of ISO Date. 
Date I get from server is 2016-03-07T00:00:00.000-06:00

And when this reaches to this function:

id FEMRepresentationValueForAttribute(id representation, FEMAttribute *attribute) 
{
    id value = attribute.keyPath ? [representation valueForKeyPath:attribute.keyPath] : representation;
    // nil is a valid value for missing keys. therefore attribute is discarded
    if (value != nil) {
        // if by mistake nil returned we still have to map it to the NSNull to indicate missing value
        return [attribute mapValue:value] ?: [NSNull null];
    }
   return value;
}

Here, [attribute mapValue:value] is returning nil. Due to which none of my dates are saved into coredata.

Can you help out how can I get this worked.

**Comment by dimazen** [comment]
Hello, @Chhaya
Can you show your mapping? There is a shortcut `+[FEMAttribute mappingOfProperty:keyPath:dateFormat:]`. Do you use it?
