### ISSUE TITLE
conditional mapping

### ISSUE THREAD

**Issue by souravray** [Yalantis/FastEasyMapping#61]
How to pass additional parameter to defaultMapping method, so I can  map conditionally like bellow

```
    if(someExternalFlag) {
         [mapping addAttributesFromDictionary:@{@"primaryID": @"user_email"}];
    } else {
         [mapping addAttributesFromDictionary:@{@"primaryID": @"user_phone"}];
    }
```

**Comment by dimazen** [comment]
For different mappings you can either pass a flag or declare two different mappings, as you did above (preferred). Actually `defaultMapping` is just a name of the method and framework doesn't aware of it, therefore you can name at as you'd like to: `+[User timelineMapping]`, `+[User detailsMapping]`. Or pass flag to method: `+[User defaultMappingWithPrimaryID:(enum UserPrimaryID)primaryID` (you can assume that `UserPrimaryID` is an `enum` with values `UserPrimaryIDEmail`, `UserPrimaryIDPhone`). 

More complicated way to do so is to check it at runtime based on availability of the keys in the JSON.
It is done like that: 

```
    FEMMapping *mapping = [[FEMMapping alloc] initWithEntityName:@"User"];
    mapping.primaryKey = @"primaryID";

    FEMAttribute *primaryID = [[FEMAttribute alloc] initWithProperty:@"primaryID" keyPath:nil map:^id(id value) {
        if ([value isKindOfClass:[NSDictionary class]]) {
            return [value objectForKey:@"email"] ?: [value objectForKey:@"phone"];
        }

        return nil;
    } reverseMap:nil];
    // we can not describe reversive mapping (user during serialization to json), because we can not dynamically specify "out" keypath.

    [mapping addAttribute:primaryID];
```

**Comment by souravray** [comment]
Thanks @dimazen this solution works for me.
