### ISSUE TITLE
is the example of Weak relationship in README.md correct?

### ISSUE THREAD

**Issue by souravray** [Yalantis/FastEasyMapping#62]
Hi,  In the _README_ the example of weak is shown like below
```
    FEMMapping *categoryMapping = [[FEMMapping alloc] initWithEntityName:@"Category"];
    categoryMapping.primaryKey = @"identifier";
    categoryMapping.weak = YES;
```
 _FEMMapping_ doesn't have a visible method/property named **_weak_**, though _FEMRelationship_ have a BOOL property name **_weak_**

**Comment by dimazen** [comment]
This one is fixed. You can check out latest README.md file.
