### ISSUE TITLE
Issue in enforcing MergePolicy of NSManagedObjectContext

### ISSUE THREAD

**Issue by souravray** [Yalantis/FastEasyMapping#64]
Hi,

My code looks like bellow

```
 _privateObjectContext = [[NSManagedObjectContext alloc]   initWithConcurrencyType:NSPrivateQueueConcurrencyType];
 [_privateObjectContext setMergePolicy:NSMergeByPropertyObjectTrumpMergePolicy];
 _privateObjectContext.parentContext = self.mainObjectContext;

 FEMMapping *mapping = [Users defaultMapping];
 NSArray *array= [FEMDeserializer collectionFromRepresentation:responseArray
                                                          mapping:mapping context:_privateObjectContext];
```

and I have set constraint on userId like this - [https://puu.sh/qE7Uw/314fa1dc42.png](https://puu.sh/qE7Uw/314fa1dc42.png)
The above code does not merge the duplicate object, and resulted duplicate rows like

```
          userId           |               userName
   --------------------------------------------------------------
           1              |                John Doe
  ---------------------------------------------------------------
           1              |                John Doe
  ---------------------------------------------------------------
```

If  change the above code to 

```
 _privateObjectContext = [[NSManagedObjectContext alloc]   initWithConcurrencyType:NSPrivateQueueConcurrencyType];
 [_privateObjectContext setMergePolicy:NSMergeByPropertyObjectTrumpMergePolicy];
 _privateObjectContext.parentContext = self.mainObjectContext;

 FEMMapping *mapping = [Users defaultMapping];
 NSArray *array= [FEMDeserializer collectionFromRepresentation:responseArray
                                                          mapping:mapping context:_privateObjectContext];
 [_privateObjectContext save:nil];
```

the the Duplicate objects merge properly and result in a single row, like 

```
          userId           |               userName
   --------------------------------------------------------------
           1              |                John Doe
  ---------------------------------------------------------------
```

Which is kind of a wired, because the same context is passed and **_save_** is call on the same context in the  _**commitTransaction**_ method. 

I know there is another way using PK FEM resolves duplicates, but I need to resolve this in merge time using a MergePolicy.

**Comment by dimazen** [comment]
The trick is that you're using constraints, that are resolved only during `save` operation:
```
The validation constraints are applied by Core Data only during a save operation or upon request (you can invoke the validation methods directly at any time it makes sense for your application flow).
```

Regarding your question: do you want to resolve duplicates using method similar to `collectionFromRepresentation`? Is that correct?

**Comment by souravray** [comment]
Hi Dima, that's correct I want collectionFromRepresentation to resolve the merge conflict.
Merge conflict is different from FEM's PK base duplicate check in the following aspects - 
1. There are multiple merge policy options. For example the **_NSMergeByPropertyObjectTrumpMergePolicy_**, which I have used in my example doesn't over ride the object completely. I only prioritized merging of changes made in the in memory object. This particularly useful for cases where two different parameters object is being updated in two different context.
2. Duplicate object can be determined based on multiple constraints.

**Comment by dimazen** [comment]
@souravray just to wrap up: method, that might looks like "synchronised collection from representation" should solve the issue by resolving duplication automatically (not involving merge policies). This actually was done before :)

**Comment by souravray** [comment]
hi Dima,
Yes I  was expecting _**collectionFromRepresentation**_ to  do this but for some strange reason it is not working. Refer the first code snippet.

**Comment by dimazen** [comment]
@souravray I got it. There was a specialised method in the past which is deleted right now. 
I have a plan for 1.1.1 release, than 1.2 that will include Carthage support, framework target and this function (but this is a 11th of Sept). How urgent is it (just to plan my schedule)?

**Comment by souravray** [comment]
That's fine :)
I have to freeze my codebase by 15th.
