### ISSUE TITLE
Relationship bindings by PK with optional relationship

### ISSUE THREAD

**Issue by heumn** [Yalantis/FastEasyMapping#79]
As per example in readme, sometimes I get this

```
{
    "result": {
        "id": 314
        "title": "https://github.com"
        "category": 4
    }
}
```
and other times I get this from server

```
{
    "result": {
        "id": 314
        "title": "https://github.com"
        "category": null
    }
}
```

Having this mapping 
```
+ (FEMMapping *)defaultMapping {
    FEMMapping *mapping = [[FEMMapping alloc] initWithEntityName:@"Website"];
    mapping.primaryKey = @"identifier";
    [mapping addAttributesFromDictionary:@{@"identifier": @"id", @"title": @"title"}];

    FEMMapping *categoryMapping = [[FEMMapping alloc] initWithEntityName:@"Category"];
    categoryMapping.primaryKey = @"identifier";
    [categoryMapping addAttributesFromDictionary:@{@"identifier": @"category"}];

    [mapping addRelationshipMapping:categoryMapping property:@"category" keyPath:nil];

    return mapping;
}
```
will crash the app when category is `null`

I do not want to use weak mapping because I still want objects with only ID created in my DB.

Suggestions for how I could solve this?

**Comment by dimazen** [comment]
@heumn Hey there! Well, there is a solution: you can inject your code into the mapping process. Lets say that you're marking your relationship as weak and therefore allow FEM to skip it. Later once "Website" has been mapped you're assigning new category in case there are no category at all. 
For example: 

```objc
FEMDeserializer *deserializer = [[FEMDeserializer alloc] initWithContext:managedObjectContext]; 
deserializer.delegate = someoneWhoConformsToDelegate;

NSArray *websites = [deserializer collectionFromRepresentation:yourJSON mapping:[Website defaultMapping]];
```

In delegate you can hook as following: 
```objc
- (void)deserializer:(FEMDeserializer *)deserializer didMapObject:(id)object fromRepresentation:(id)representation mapping:(FEMMapping *)mapping {
    if ([object isKindOfClass:[Website class]]) {
        Website *website = (Website *)object;
        if (website.category == nil) { 
            // assign default value here
        }
    }
}
```

**Comment by heumn** [comment]
Got it, thanks a lot for the help :) 💯

**Comment by dimazen** [comment]
@heumn You're welcome! 

Forgot to add another one option: 
You may map category id in the following manner: bypass any valid number and replace null by 0. 
It will affect your logic because for every website without category FEM assign single fake category with id == 0. But it will also simplify mapping code a lot. It also removes requirement to set relationship to the weak one. 

Hope that helps.
