### ISSUE TITLE
EasyMapping vs FastEasyMapping

### ISSUE THREAD

**Issue by jcavar** [Yalantis/FastEasyMapping#84]
Hi,
I have more of general question about these two libraries. We evaluated them both recently and they look quite similar, even bugs we encountered were the same in both of them.  API is quite similar, performance measurements as well.

I am wondering if there is something in EasyMapping that is not available in FastEasyMapping or other way around? 
If not, would it make sense to merge them? That would simplify choice of mapping library and would probably make that one much better.

**Comment by jcavar** [comment]
I asked the same thing on EasyMapping:

https://github.com/lucasmedeirosleite/EasyMapping/issues/153

**Comment by dimazen** [comment]
I posted my answer in the https://github.com/lucasmedeirosleite/EasyMapping/issues/153
