### ISSUE TITLE
Remove or update performance graph

### ISSUE THREAD

**Issue by jcavar** [Yalantis/FastEasyMapping#85]
As mentioned [here](https://github.com/lucasmedeirosleite/EasyMapping/issues/153) performance comparison of EasyMapping and FastEasyMapping is not correct anymore.

**Comment by dimazen** [comment]
I left a comment above the performance graph: 
> Benchmark done on June/2014. Results may be outdated (EasyMapping performs nearly identical nowadays).

I'll update it with 1.3 that includes additional performance improvement
