### ISSUE TITLE
Map representation part for property

### ISSUE THREAD

**Issue by stasivanov** [Yalantis/FastEasyMapping#95]
I have JSON, that has 
`someObjectIDs : [1, 2, 3]`

Instead of storing this as Array of numbers, I want to wrap this to some class. Like I want to map `[1, 2, 3]` to `[{ "id" : 1 }, { "id" : 2 }, { "id" : 3 }]`, and proceed mapping of objects with the new version of representation. Map closure of the FEMAttribute does a little bit different thing, since it asks for the actual result of parsing. And I would use that, if I would be able to use the context of the NSManagedObject... But in map closure, I cannot wrap JSON and return smth like "FEMDeserializer.collectionWithNextJSON", since I don't have access to NSManagedObjectContext, that is used to parse the parent object...

I would like to have a separate block for wrapping representation, instead of having access to context property.

Is it possible to add this?

**Comment by dimazen** [comment]
Hello, @stasivanov 
Not very clear to me what you're trying to do. 
Are those objects NSManagedObject subclasses? If so - you still can map array of ids to those objects by specifying an empty keyPath. 

```objc
FEMMapping *parent = [FEMMapping ...];

FEMMapping *child = [FEMMapping ...];
child.primaryKey = @"someID";
[child addAttributeWithProperty:@"someID" keyPath:nil]; // thats the trick

[parent addToManyRelationshipMapping:child forProperty:@"children" keyPath:@"someObjectIDs"];
```

**Comment by stasivanov** [comment]
Wow, I didn't know that trick :) Thank you very much!
